### ISSUE TITLE
Send a DM to people who we assign a Bastion / Colossus ticket to

### ISSUE THREAD

**Issue by Maelstromeous** [dignityofwar/digbot#110]
Currently we have to explain how to redeem bastion / colossus tickets every time we give them, would be nice to DM them info, exactly how the Forced PTT role works.

Wording:

**You have been awarded an war asset ticket!**

Congrats on winning your ticket! At DIG we like to give everyone an opportunity to play with the War Asset toys (Bastion / Colossus) for PS2, but in order to know is elegible we use roles on Discord to track this.

**How do I redeem my ticket?**

Quite simply contact a DIG officer or Leader and we'll promote you temporarily to allow you to pull the asset, remove your ticket then demote you back to your previous rank, this is the most efficent way we know to enable our non-officer members to use the war assets.

Feel free to ping @PS2/DIG/Officers or @PS2/DIG/Leaders in any of our channels to ask to pull the war asset!

**Comment by microwavekonijn** [comment]
Solved with the addition of dm's on role assignment.
