### ISSUE TITLE
Rework the Modular Channel System

### ISSUE THREAD

**Issue by microwavekonijn** [dignityofwar/digbot#116]
The modular channel system has been removed to get v3 ready for production. Needs to be readded and fixed.

**Comment by Maelstromeous** [comment]
Truth be told this potentially isn't needed any more, we kinda filled this hole with Mee6 and it's channel hub system.

**Comment by microwavekonijn** [comment]
I am going to leave the issue up as most of the code is done and just needs to be finished at some point.
