### ISSUE TITLE
Legacy Issue: !play phase 2™

### ISSUE THREAD

**Issue by JamesLongman** [dignityofwar/digbot#18]
This issue requires a refactor of the play.js file, this is by far the most complicated code in our bot. For your own sanity only attempt if you have a good grasp of node.js

Still it's one of the most loved features of our bot and better volume control is probably the number 1 request so I'd love to get some work done on this once we're stable

Original issue by James:
> Gunna leave this for at least a week maybe much longer while I collect things that need doing with the feature, edit OP with things that need looking at
> 
> - [ ]  Gueren no yojo or whatever it is that drags on so long I'll cut that from the "fun" playlist, or maybe swap to its TV version
> - [ ]   Bad blood in 10's playlist is an instrumental... This is what happens when you only listen to the first 4 secs of songs, I guess people will have to sing it for now
> - [ ]   Pass on coded playlist volumes, not as consistent as I'd like (Wait till discord.js v12, maybe will fix global stream volumes) [v12 would you believe it is still not out, they may have fixed this in a minor release]
> - [ ]   See if it's possible to get song names for YT video requests (should not be too hard)
> - [ ]   See if it's possible to get song names for YT playlist requests (I'd guess this'd be a lot harder)
> - [ ]   See if anti duplication can remember the array index provided immediately prior with larger arrays to improve rotation. Up to 10?
> - [ ]   Have bot playback stop automatically if all members leave the channel
> - [ ]   Make sure replies are sent to all commands
> - [ ]   Make sure to let people know if requests are bad
> - [ ]   Have a good look at the code and make sure we don't have any processing/memory black holes
> - [ ]   Make sure to tell people if they're doing silly things like including a &t= timestamp
> - [ ]   Allow multiplications to channel volumes instead of just up and down (enforce absolute limit)
> - [ ]   Investigate if it's possible to have the bot swap between channels on request
> - [ ]   Investigate playlist sequential/shuffle modes
> - [ ]   Investigate songs randomly skipping before they're finished
> - [ ]   Allow !play queue, to display queue in channel
> 
> Maelstromeous:
> You should certainly be able to get the video title, would be sufficient.
> 
> James:
> Good amount of time passed, this is however gunna be dependent on discord.js v12 so I'll postpone until it's out
> 
> Maelstromeous:
> What in particular is dependant on v12?
> 
> James:
> General stability plus volume overhaul, connection, playback and random crashes should all hopefully be fixed but it'll be massively breaking apparently so I kinda wanna wait to overhaul it
> 
> Maelstromeous:
> Okies

**Comment by microwavekonijn** [comment]
I am just going to leave this here. When a subbot is playing in a channel and it becomes empty, it should stop automatically. Now it just keeps going.
