### ISSUE TITLE
Legacy Issue: Couple of crashes

### ISSUE THREAD

**Issue by JamesLongman** [dignityofwar/digbot#19]
Original issue by James:

> Little bit of instability atm had a couple of interesting crashes that need looking into:
> ```
> 2:29:17 AM [ERROR] (Crash Handler) [2:29:17 AM] Uncaught Exception Crash
> - Last Events:
> - [2:29:17 AM] (Commands Antispam) releaseUser
> - [2:29:17 AM] (Commands Antispam) releaseCommand
> - [2:29:17 AM] (admin.js) fiveMinCheck
> - Last Messages Recieved:
> - [1:01:17 AM] (Dignity of War) ?
> - [1:15:56 AM] (Dignity of War) allso
> - [1:15:57 AM] (Dignity of War) http://www.independent.co.uk/life-style/health-and-families/health-news/hiv-aids-vaccine-therapy-trials-no-daily-drugs-art-irsicaixa-barcelona-beatriz-mothe-a7596521.html
> - TypeError: Cannot read property 'roles' of null
>     at Object.module.exports.getRoles (/var/www/dignityofwar.com/bot/src/lib/server/server.js:133:33)
>     at Object.module.exports.getRole (/var/www/dignityofwar.com/bot/src/lib/server/server.js:123:19)
>     at Object.module.exports.release (/var/www/dignityofwar.com/bot/src/lib/admin/antispam/mentionspam.js:159:31)
>     at Timeout.fiveMinCheck [as _repeat] (/var/www/dignityofwar.com/bot/src/lib/admin/admin.js:110:17)
>     at Timeout.wrapper [as _onTimeout] (timers.js:417:11)
>     at tryOnTimeout (timers.js:224:11)
>     at Timer.listOnTimeout (timers.js:198:5)
> ```
> 
> ```
> 9:39:54 AM [ERROR] (Crash Handler) [9:39:54 AM] Uncaught Exception Crash
> - Last Events:
> - [9:39:31 AM] (discordbot) presenceUpdate
> - [9:39:52 AM] (discordbot) presenceUpdate
> - [9:39:54 AM] (!sfx) release
> - Last Messages Recieved:
> - [9:21:46 AM] (Dignity of War) Stop giving it weed FFS
> - [9:39:01 AM] (Dignity of War) !sfx akbar
> - [9:39:24 AM] (Dignity of War) !sfx admin
> - TypeError: Cannot read property 'channelName' of undefined
>     at VoiceConnection.connection.on (/var/www/dignityofwar.com/bot/src/commands/sfx.js:206:78)
>     at emitNone (events.js:91:20)
>     at VoiceConnection.emit (events.js:185:7)
>     at VoiceConnection.disconnect (/var/www/dignityofwar.com/bot/node_modules/discord.js/src/client/voice/VoiceConnection.js:150:10)
>     at VoiceChannel.leave (/var/www/dignityofwar.com/bot/node_modules/discord.js/src/structures/VoiceChannel.js:126:69)
>     at Timeout.release (/var/www/dignityofwar.com/bot/src/commands/sfx.js:284:27)
>     at tryOnTimeout (timers.js:224:11)
>     at Timer.listOnTimeout (timers.js:198:5)
> ```
> 
> ```
> 10:38:12 PM [ERROR] (Crash Handler) [10:38:12 PM] Uncaught Exception Crash
> - Last Events:
> - [10:38:05 PM] (discordbot) message
> - [10:38:05 PM] (discordbot) message
> - [10:38:12 PM] (!sfx) release
> - Last Messages Recieved:
> - [10:37:22 PM] (Miller Server Community) https://gfycat.com/PrestigiousHiddenEasternglasslizard
> - [10:37:41 PM] (Dignity of War) !sfx admin
> - [10:38:05 PM] (Dignity of War) !sfx bad
> - TypeError: Cannot read property 'removeAllListeners' of null
>     at VoiceConnection.cleanup (/var/project/node_modules/discord.js/src/client/voice/VoiceConnection.js:314:7)
>     at VoiceConnection.disconnect (/var/project/node_modules/discord.js/src/client/voice/VoiceConnection.js:299:10)
>     at VoiceChannel.leave (/var/project/node_modules/discord.js/src/structures/VoiceChannel.js:126:69)
>     at Timeout.release (/var/project/src/commands/sfx.js:284:27)
>     at ontimeout (timers.js:365:14)
>     at tryOnTimeout (timers.js:237:5)
>     at Timer.listOnTimeout (timers.js:207:5)
> ```
> 
> Need to identify the cause of and fix all

**Comment by microwavekonijn** [comment]
First error seems to have been resolved when discord.js got updated.
