### ISSUE TITLE
Get DIGBot running on staging

### ISSUE THREAD

**Issue by JamesLongman** [dignityofwar/digbot#3]
Rellies on #2 

Once the staging server is up we can work on getting the bot hosted and running on it. At this stage we should ensure that the bot is at least as stable as the current version being run on live.

Hosting relies on Llama, once he works out how the bot is going to be hosted by the community we should be able to implement this soon as the initial master branch code will server for this purpose.

**Comment by microwavekonijn** [comment]
DIGBot is running, but does not automatically update yet. This will be addressed soon.
