### ISSUE TITLE
Legacy Issue: DIGBot isn't acknolwedging !play playlist commands

### ISSUE THREAD

**Issue by JamesLongman** [dignityofwar/digbot#37]
Original issue by Maelstrome

Requires confirmation and repro

**Comment by microwavekonijn** [comment]
I have already been messing with the play command. The fix is very easy as it requires updating the dependecies(mostly ytdl-core) and we need to install ffmpeg(don't really know why we need it now as we didn't before).

**Comment by JamesLongman** [comment]
I believe this is a separate issue related to the handling of requests
