### ISSUE TITLE
Many SFX and music assets have bad links

### ISSUE THREAD

**Issue by JamesLongman** [dignityofwar/digbot#38]
These could be updated but this would require volume configurations. If #18 was completed first, hopefully, we could get volume normalisation in that so it would just be a matter of replacing links.

Really these links have no business being hardcode and should be in a database anyway, handling for bad links is included in the bot so this isn't a critical issue

I believe @microwavekonijn has already got some new links ready posted into the dev channel on discord

**Comment by microwavekonijn** [comment]
#41
