### ISSUE TITLE
Set up deployment infrastructure

### ISSUE THREAD

**Issue by JamesLongman** [dignityofwar/digbot#4]
We need a set up where changes to the staging and master branches are automatically deployed.

How this will run entirely depends on how Llama chooses to set up our hosting

**Comment by JamesLongman** [comment]
Micro has suggested we use Dockerhub to automate builds of staging and production from staging and master respectively. I will look into setting up this up

**Comment by JamesLongman** [comment]
Set up a dockerhub repo at https://hub.docker.com/r/dignityofwar/digbot/

I believe it is now set up to automatically build on changes to staging and master. This will then be automatically deployed on our server.

One thing to watch out for is that I needed to specify the dockerfile locations for the builds to work and they will move from ./ to ./docker/ in the first patch

**Comment by microwavekonijn** [comment]
Basic config for dockerhub:
```
Production
Type:			Branch
Name:			master
Dockerfile Location:	/docker
Docker Tag Name:	latest

Staging
Type:			Branch
Name:			staging
Dockerfile Location:	/docker
Docker Tag Name:	staging

Dev
Type:			Branch
Name			develop
Dockerfile Location:	/docker
Docker Tag Name:	dev
```

I agree that the dockerfile should be in the root. Also we can later add a builds for specific versions of the bot using tags. Also, correct me if I am wrong, but we don't work directly of the develop branch and everything added to it is done by PRs. If that is true then it doesn't really make sense to have a staging and develop branch.

**Comment by JamesLongman** [comment]
I would be strongly against changing our branch setup as it works well.

I did see that docker hub could do versioning through tags but I would really prefer to keep that versioning github side. Master should always be the current production, and staging should always be the current staging, dockerhub can be easily set to run something master:latest and staging:latest builds so that would work well for us. If we want to roll a specific version we could always just pull that github tag onto the branch we want.

We do work off of develop and you should always branch from it as it will be the most current major branch. Commits directly to develop are cool too for small edits to patches, all contributors should be able to push it, it's just bad form for anything material as it largely bypasses our review process. The general idea is that we build patches on develop branching off of it with smaller PRs and edits reviewing as we go, and when we're happy we can have one final big review as we PR it to staging.

**Comment by microwavekonijn** [comment]
Okay, sounds good. With the versioning, we would keep it on the github side. For instance we would merge version 1.1 from staging to the master, we would tag the last commit with something like "v1.1" on github. Then we could configure dockerhub to also build images with tags like v*.*. That way we have a history of all our builds.

**Comment by microwavekonijn** [comment]
Docker Hub is setup and works. Staging is up and running. ~~Only thing left is automatic redeployment~~ #3
