### ISSUE TITLE
MCS currently disabled

### ISSUE THREAD

**Issue by JamesLongman** [dignityofwar/digbot#49]
Modular Channel System: Adaptively create new voice channels as others become full, deletes them when no longer in use.

MCS system is currently disabled, it was probably broken in the subchannel discord update. Someone will need to communicate with the community staff if they want this feature re-implimented, and depending on their answer either remove it from the project files or update it to work in line with the new subchannel system.

A quick fore-warning: MCS code is some of the most complex code in the project

**Comment by microwavekonijn** [comment]
What is broken? I tried it out on my local build and it seems to work fine.

**Comment by JamesLongman** [comment]
The MCS was not built for subchannels so it may need updating to account for them.

The reason it was disabled however is I'm fairly sure the server's channels did not match the ones we had on file which is an easier fix
