### ISSUE TITLE
Refactor how "\\" is handled in sub-bots.js

### ISSUE THREAD

**Issue by JamesLongman** [dignityofwar/digbot#51]
Currently, every single time a token or id is used in sub-bots.js, the string is parsed via .replace(/\\/g,'') to remove the "\\" that is a side effect of how it is received in Travis CI cases.

Instead of the string being passed every time it is called from the subBots object, the object should be parsed once on setup so subsequent calls do not need to use replace. It will obviously be much more efficient

**Comment by microwavekonijn** [comment]
Is this because of the way the bashscript writes them to the config json files or is this because they are entered like that in travis?

**Comment by JamesLongman** [comment]
That is an excellent question this will indeed deserve revisiting after the next patch. I'll try and test it without risking rolling 12 env variables

**Comment by JamesLongman** [comment]
This will be tested with the #57 PR, added . and _ characters to the last dummy token so once we get the variable passed correctly in the PR we'll be able to also see if they are being received escaped, I suspect if we pass using this method they will not be

**Comment by JamesLongman** [comment]
Test showed that the characters are no longer escaped, all .replace handling can be removed

**Comment by microwavekonijn** [comment]
When I worked on the refactor of config they weren't there yet and when I merged the changed of CI into that branch that change was not merged. So the #55 does not use the replace function and the tests passed without it.

I checked it just now, I didn't know that I had done it.
