### ISSUE TITLE
PR from a fork will run CI and fail

### ISSUE THREAD

**Issue by microwavekonijn** [dignityofwar/digbot#56]
So any PR will trigger CI and only if it is from a fork it will fail due to a time-out. I don't think it suppose to run in the first place.
https://travis-ci.org/JamesLongman/DIGBot/builds/446158266

**Comment by JamesLongman** [comment]
Yeah the builds will run but they will not have access to travis env variables. That's by travis design and can not be changed. It's probably possible to set Travis to let the author know they need to PR from a repo feature branch but it's not like we can't just tell people too
