### ISSUE TITLE
Incorrect root does not cause test failures

### ISSUE THREAD

**Issue by JamesLongman** [dignityofwar/digbot#60]
test/project-files.js and /test/src/assets/pictures/picture-assets.js tests should fail without a correct root but don't

These tests certainly used to work and as far as I know they haven't been changed since they did so I'm not sure why they're not working.

**Comment by microwavekonijn** [comment]
The reason why the test doesn't work is because existsSync doesn't throw an error, it will return boolean depending on whether the files exists. I assume before the existsSync function was used an other method was used where it tries to read the file and throws and error when it doesn't exist.

**Comment by JamesLongman** [comment]
Yeah, I think I recall it being updated as we used a previous method which node depreciated previously. I guess when we changed the method we didn't change the tests to booleans rather than catching errors, which quite frankly is an improvement
